services:
  frontend:
    build: ./frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app          # source code (hot reload)
      - /app/node_modules        # keep node_modules inside container
    environment:
      - CHOKIDAR_USEPOLLING=1    # helps file watching in Docker
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    build: ./backend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app           # <-- removed stray quote
      - /app/node_modules
    command: npm run start:dev
